### ISSUE TITLE
SiteGround Filter

### ISSUE THREAD

**Issue by pandjarov** [wp-media/imagify-plugin#184]
We need to discuss and re-do this piece of code:
```php
add_filter( 'http_request_args', 'imagify_siteground_change_user_agent', 10, 2 );
/**
 * Filter the arguments used in a HTTP request to change the User Agent for requests "to self".
 * SiteGround blocks (error 403) HTTP requests with a User-Agent containing the site's domain.
 * The problem is that, for a given site at https://example.com, WordPress uses the UA `WordPress/4.8.2; https://example.com`.
```

We do not block those requests, you're probably passing a post request with empty referrer or something else. I could setup a test environment so we can have this solved.

This filter breaks our cache testing functionality and we already have users reporting it.

**Comment by Screenfeed** [comment]
Hello.

One of our clients reported indeed this problem yesterday.
The thing is that we encountered this issue many times with our plugins, and the solution was always to change the user agent. And of course I made many tests to be sure it was the source.

To be sure, I just ran some tests again, using Postman, and that's when it gets "funny":
- Requests to site A with site A address in UA: OK.
- Requests to site A without site A address in UA: OK.
- Requests to site B (also on SG) with site B address in UA: OK.
- Requests to site B without site B address in UA: OK.
- Requests to site B with **site A** address in UA: **KO**.

So, I don't know what to thing about that, do you have any explanation?

So far, the only solution I can think of, is to limit our filter to `admin-ajax.php`, `admin-post.php`, and `wp-cron.php`, so we don't change the UA for your cache tests..

**Comment by Screenfeed** [comment]
Ah, made more tests.
My last item in my previous comment should be replaced by:
* Requests to site A with `ning` in UA: OK (site's domain contains it).
* Requests to site B with `ning` in UA: KO (site's domain doesn't contain it).

**Comment by pandjarov** [comment]
Found a bug in the nginx rules and indeed it waas hitting a blacklist. Could you check it again please?

**Comment by Screenfeed** [comment]
Ho, nice, now we know where this behavior comes from, thanks a lot.
Unfortunately this was 2 months ago, we don't have access to this website anymore :(

**Comment by pandjarov** [comment]
Please check this customer if you need: https://wordpress.org/support/topic/incompatibility-with-sg-optimizer/

However, that should have been fixed so please remove the filter so we can avoid such complaints in the future.

**Comment by Screenfeed** [comment]
Hi there.

We still have this issue on this site: http://smashingcoding.com.
To reproduce, try a GET or POST request on any page, with the User-Agent `ning`: error 403.
Well, in this case it's not an issue since `ning` is not in the site's domain, but what about sites where it is?

So, I guess I'll continue to randomize the User-Agent, but only when requesting **/wp-admin/admin-ajax.php**, **/wp-admin/admin-post.php**, and **/wp-cron.php**.

I think this solution will be fair for both sides, don't you think?
